### ISSUE TITLE
De-duplicating on @receiver

### ISSUE THREAD

**Issue by candlerb** [prymitive/karma#1578]
I have alertmanager routing configured so that some alerts are sent to multiple receivers (using `continue: true` in routing rules)

I'd like to get karma to display only a single instance of each alert, regardless of how many `@receivers` there are.  For instance, it could strip `@receiver` off all alerts and then de-duplicate.

I tried:

```
receivers:
  keep: [nothing]
```

but this gets rid of all the alerts entirely.  Then I tried:

```
labels:
  strip:
     - "@receiver"
```

but this doesn't make any difference (I see both alerts, with their `@receiver` labels)

Any clues?

**Comment by prymitive** [comment]
`@receiver` is not a real label so `labels:strip` won't work with it.
If you have an alert that goes through multiple receivers in alertmanager then those become essentially different alert trees in karma. There isn't really a good way to merge that back because each of those receiver trees might have different `group_by` configuration, so they can be unique.
In the environment I work with there's a receiver per team, so each receiver tree contains all alerts for given team, any merging that back into a single tree would destroy this per team view.

I think that your options here are: 
1. have some receiver that gets all alerts you want to see in karma na simply filter by that receiver in karma UI - `@receiver=foo` (you might want to add it to default filters in the config)
1. strip all but one receiver in karma config

**Comment by candlerb** [comment]
Thanks for the explanation of the behaviour.

I have some cases of overlapping teams/responsibilities (hence multiple receivers).  I'll either make larger single receivers which expand to the relevant people across teams, or I'll add a "karma" receiver for everything and filter on that.

Cheers!
