### ISSUE TITLE
Export alerts

### ISSUE THREAD

**Issue by skpenpen** [prymitive/karma#1666]
Can you add an export functionnality to the dashboard ?

**Comment by prymitive** [comment]
Not sure what you mean exactly, but if you want to archive alerts then you should setup [alertmanager webhook receiver](https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver), like https://github.com/cloudflare/alertmanager2es

**Comment by skpenpen** [comment]
I mean, it would be great to have an export function which export into csv/excel (labels exporter configured via config file) all alerts displayed for the current filter.
Its not about archieving, its about giving the possibility to export into a "manager comprehensive format" the current alerts, if you know what i mean :)

**Comment by prymitive** [comment]
You can export from ElasticSearch if you setup webhook receiver. "Managerial" features are a non-goal here.

**Comment by skpenpen** [comment]
I see and undestand the solutions you propose, but it seems a bit overkill to configure webhook, dev an alertmanager webhook transformer into Elastic, just to export a json response from the alertmanager api into a comma delimited file...

Since karma, which is great and we love, offer a way to connect to multiple alertmanger, filter alerts, display labels we want etc, i think its a would be great to also have an export function.

But if i'm the only one to see the gain, ok, maybe i'll dev it myself...

**Comment by Mario-Hofstaetter** [comment]
@skpenpen There may be another way for you to do it.
Maybe you alreaddy use grafana, you can use it to display active alerts and export them.

- PromQL Query `ALERTS` returns all active & pending alerts, `ALERTS_FOR_STATE` returns timestamp since when the alarm is active
- Use Query Mode `Table` and table panel to display, unwanted columns (like `__name__`) can be hidden.
- Use Panel Export to CSV to get the data

Its not perfect but better than screenshotting 😄 and certainly easier than setting up Elastic.
If you want a _pretty_ excel you can make one and link the exported CSV to it.

![grafik](https://user-images.githubusercontent.com/33002073/82154991-fce7d680-9871-11ea-8fca-6e8479988427.png)

![grafik](https://user-images.githubusercontent.com/33002073/82155025-5d771380-9872-11ea-8587-393080aac7ae.png)

The CSV export does not include columns that where hidden in the table panel, if you have lots of labels.
