### ISSUE TITLE
@alertmanager label not allowed as a choice for multiGridLabel or sort label

### ISSUE THREAD

**Issue by asetty** [prymitive/karma#1775]
Would it be possible to make this an option or is there an explicit reason to not add this?

**Comment by prymitive** [comment]
`@alertmanager` is not a real label, but yes, I could look into adding support for that

**Comment by asetty** [comment]
Thanks for taking a look.

**Comment by asetty** [comment]
Accidentally pressed "Close and comment" there...

Anyways, thanks for taking a look. In my use case, we could add a global external label to the prometheus config for "cluster", but it would end up being redundant if the @alertmanager label could be used for sorting/multi grid. Also some alerts I have will have all of the same labels, only differing by @alertmanager and it would be nice if these were not deduped.

Maybe a more general way to approach this could be a `labels` field in the `alertmanager.servers` config where certain labels are added to all alerts scrapped from an instance.

**Comment by prymitive** [comment]
Adding both `@receiver` & `@alertmanager` as multi-grid labels is pretty easy, so I'll add that.
One little annoyance is that a clustered alertmanager with `@alertmanager` based multi-grid will have same alerts under each `@alertmanager` value.
Having multi-grid with grid per cluster would be great, but that needs some meaningful cluster names somewhere. Currently clusters are auto-detected from alertmanager API, karma config has a flat list of all instances, and the API doesn't expose any sort of label or name for each cluster. Which is why silence form dropdown has "name1 | name2" label for each cluser.
A better solution might be to have expected cluster topology in karma conf and warn if detected topology (via API) differs from it. This would give us useful names and we could easily add something like `@cluster` filter & multi-grid option.

**Comment by prymitive** [comment]
Merged #1825 that adds:
- `@cluster` filter
- `cluster` option for every [alertmanager config section](https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#alertmanagers)
- ability to use `@receiver`, `@cluster` and `@alertmanager` as multi-grid options

**Comment by prymitive** [comment]
You can test it on http://karma-demo.herokuapp.com/

**Comment by asetty** [comment]
This is great and exactly what I was looking for, good thinking on adding the @cluster option as well.

Thanks for addressing this so quickly!

**Comment by asetty** [comment]
Are you planning to cut a release that will include these changes soon? If so, I'm trying to avoid using `latest` or building the image myself to deploy. :)

**Comment by prymitive** [comment]
Yes, this week
