### ISSUE TITLE
Label key "alertname" should be less visually dominating

### ISSUE THREAD

**Issue by vonneudeck** [prymitive/karma#18]
This is a great tool and it really helps to see things clearer. I read about it on the Prometheus-User-Mailinglist. Thank you very much for presenting it there and moving it over here.

Following the spirit of clarifying I think the actual alertname (the value) should be more prominent than the label’s key. So in `alertname: HardToRead` the string `HardToRead` should be more prominent than the `alertname`.
It is good that the keys are so prominent for other labels, but for alertname less would do because one might use this to find an alert by skimming over and every alert has this label, seeing the precise letters of its key in detail is not as important compared to other labels’ keys.

I am not sure how to do this the best way, but here are a few proposals/ideas:
- left-align the label (to simplify vertical skimming)
- change the font redendering for the `alertname` key
  - less bold
  - less contrast
  - not render the key `alertname` at all

What do you think?

**Comment by prymitive** [comment]
I think you're making a good point, I think it makes a lot of sense to put more focus on label values since keys will be repeated but values are going to be more unique.
Now when it comes to the implementation details of how this can be accomplished let's remember that `alertname` is just one of labels, it's a little special since it's injected by Alertmanager, but other than that it's simply yet another label.
You might have noticed that labels can have unique colors, those are calculated from the `key: value` pair. I did try to experiment with different styles where both `key` and `value` would have it's own color, but that was too noisy, some more experimentation could be possible there, but I doubt we can get more value there without adding noise, which would nullify said value.
We could also try to (as you suggest) tweak the font and the general style of the key, I think it requires a demo to see if that's useful.
Another option I considered in the past, just never implemented, is what you also have as one of the suggestions - don't display the key (`alertname` in this case) - what I was thinking is that there's a bunch of "standard" keys, like `@alertmanager`, `@receiver` and `@alertname` which are usually quite obvious (as in once you know that's alertname in the title you don't need to see that key again) and I wanted to only render the value until user hovers the cursor over the label, in which case we would expand it into a full label with both key & value.
Finally there's the case of which of those can be applied as a general rule to any label and which are `alertname` specific - I think the last option seems the best for me right now, dropping keys from well known labels could help reduce visual clutter, but still allowing user to still see the key if they are confused or unsure about it.

**Comment by prymitive** [comment]
Shrinking/expanding label name will be tricky since resizing any label might move it to the next line losing hover state, so a tooltip/popover would be a better solution (but only for "well known" labels).
Names could be rendered smaller than values and with different color, but that will require backend changes and a bit of refactoring

**Comment by prymitive** [comment]
Would this be more readable? I feel like the font might be a little too small now

<img width="1610" alt="screen shot 2018-10-11 at 16 06 45" src="https://user-images.githubusercontent.com/114288/46814012-bcf46f80-cd6f-11e8-9216-c485f1fd058d.png">

**Comment by vonneudeck** [comment]
First of all please excuse me for not answering before, somehow the notifications got filtered away by accident. I am so sorry, I value your wor and it was not on purpose. 😞

I agree, the smallness is a bit too small for my taste. Also if the size varies too much we always have content that is either too large or too small. Not ideal.
I still think that aligning the alertname to the left instead of centering it would help.

**Comment by prymitive** [comment]
No worries and thanks for feedback. This is something that I don't have any strong opinion on so I appricate getting some input.
I feel like not centering alerts in the title (which I think is what you mean by `aligning the alertname`) would be good, since alertname label would always be in the same place. I'll try pushing layout changes to http://karma-demo.herokuapp.com. Thanks!

**Comment by prymitive** [comment]
Please see https://github.com/prymitive/karma/pull/147#issuecomment-429648014 for the current changes

**Comment by vonneudeck** [comment]
This looks nice 🤩
I love how the different colour used for some keys makes them really easy to differentiate from the value. E.g.: `time`, `alertname` and `device`. Surely adding `instance` would be good, maybe even for all labels?
It is tricky though to ensure a decent contrast for all colours and combinations.

**Comment by prymitive** [comment]
Which labels are coloured is configured by the user, the only default is the black background for alertname, since that’s the only guaranteed label (injected by alertmanager).
See Labels section on https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md

**Comment by prymitive** [comment]
> It is tricky though to ensure a decent contrast for all colours and combinations.

Yes, but I'm hoping I can improve this. Right now it's static, but for all generated colors we calculate brightness to decide if we should use bright or dark font. I want to see if I can use this information to pick better looking font color for the name part.
