### ISSUE TITLE
Strip @cluster or hide it when only one AM configured

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#3994]
Hello @prymitive,
I've been trying to hide `@cluster` via labels/strip feature in #3221 but that doesn't seem to work (karma 0.98), is that expected ? Alternatively I'd like to suggest hiding @cluster by default when only one AM is configured, similar logic as @receiver in #1715, what do you think?

Thank you!

**Comment by prymitive** [comment]
I could swear that's what was suppose to happen (hide `@cluster` if there's only one in the config). Must have changed that accidentally at some point. Raised #3998 for a fix.
Hiding won't work, `@cluster` is needed otherwise you can have 2 identical alerts with no way of telling the difference between them.
