### ISSUE TITLE
grid sorting looks like not working

### ISSUE THREAD

**Issue by freeseacher** [prymitive/karma#866]
![image](https://user-images.githubusercontent.com/289277/62720042-7c09cd80-ba09-11e9-8eaa-e0649273420c.png)
that is how my dashboard look alike
but according to config 
```
    listen:
      address: "0.0.0.0"
      port: 80
      prefix: /
    log:
      config: false
      level: warning
    alertmanager:
      interval: 60s
      servers:
        - name: global
...
        - name: RED
...
        - name: BL
..
        - name: k8s
..
    annotations:
      default:
        hidden: true
      hidden:
        - help
      visible:
        - summary
        - runbook
    debug: false
    labels:
      color:
        unique:
          - team
          - tier
        custom:
          priority:
            - value_re: "(p|P)3"
              color: "#87c4e0"
            - value_re: "(p|P)2"
              color: "#ffae42"
            - value_re: "(p|P)1"
              color: "#ff220c"
            - value_re: ".*"
              color: "#736598"
      keep: []
      strip:
        - "@receiver"
        - job
        - monitor
    receivers:
      keep: []
      strip:
        - 'null'
        - heartbeat-email
        - heartbeat-http
        - dev_null
        - jnxJsNatSrcXlatedAddr
    grid:
      sorting:
        order: label
        reverse: false
        label: priority
        customValues:
          labels:
            priority:
              p1: 1
              P1: 1
              p2: 2
              P2: 2
              p3: 3
              P3: 3
              p4: 4
              P4: 4
              p5: 5
              P5: 5
```
i expecting all alerts with p2 priority should be on the top. but there are 2 alerts with p2 and they are in the middle of dashboard. 
![image](https://user-images.githubusercontent.com/289277/62720212-d3a83900-ba09-11e9-920d-25a5362faf22.png)

Am my expectations wrong ?

**Comment by prymitive** [comment]
Sorting is best effort since the grid is layout to pack groups in a masonry style layout. This means that there might be some individual groups not respecting the ordering but I doubt it would result in the order as you have on the screenshot.
Can you double check that you didn't set a different sorting config in the UI modal dialog (gear icon, near the bottom)?
I just merged moving sorting to the backend (for performance reasons) so if it's a bug I might fixed  it, or it's still there, or I added new bugs. If you don't have any override config in the UI can you check if the `latest` docker image (https://cloud.docker.com/repository/docker/lmierzwa/karma/tags) still has this issue?
Thanks!

**Comment by freeseacher** [comment]
i haven't set sorting on my side on 0.42
0.43 fixes the issue. all alerts looks sorted.
